import threading
from pynput import keyboard

from src.utils.get_key_pressed import normalize_key
from src.hotkeys.windows_hook import WindowsKeyboardHook


class HotkeysManager:
    HOLD_THRESHOLD = 0.15

    def __init__(self, main_app):
        self.main_app = main_app
        self.settings = main_app.settings
        self.macro = main_app.macro

        self.held_keys = set()

        # Keys whose KEY-DOWN was actually suppressed.
        # A key-up is suppressed only when its corresponding key-down
        # was suppressed. This prevents stuck Shift/Ctrl/Alt/Win.
        self.suppressed_keys = set()

        # One-shot combinations already activated while held.
        self.active_combos = set()

        self._lock = threading.RLock()

        self.mode1_rapid_active = False

        self.mode2_mouse_active = False
        self.mode2_mouse_hold = False
        self.mode2_mouse_timer = None

        self.keyboard_hook = WindowsKeyboardHook(
            self._keyboard_event
        )

        if not self.keyboard_hook.start():
            raise RuntimeError(
                "Windows keyboard hook failed to install. "
                f"Win32 error: {self.keyboard_hook.last_error}"
            )

    # ==============================================================
    # Configuration helpers
    # ==============================================================

    def _get_mode(self, mode):
        return self.settings.settings_dict.get(mode, {})

    def _get_combo(self, mode, option):
        value = self._get_mode(mode).get(option, [])

        if isinstance(value, str):
            value = [value]

        if not isinstance(value, list):
            return set()

        result = set()

        for item in value:
            key = normalize_key(item)

            if key:
                result.add(key)

        return result

    @staticmethod
    def _combo_key(combo):
        return tuple(sorted(combo))

    @staticmethod
    def _combo_is_held(combo, held_keys):
        return bool(combo) and combo.issubset(held_keys)

    # ==============================================================
    # Windows hook callback
    # ==============================================================

    def _keyboard_event(self, vk_code, is_key_down, is_key_up, flags):
        # Ignore input generated by this application.
        if flags & 0x10:  # LLKHF_INJECTED
            return False

        key = self._vk_to_key(vk_code)

        if key is None:
            return False

        # ----------------------------------------------------------
        # KEY DOWN
        # ----------------------------------------------------------

        if is_key_down:

            # Ignore Windows auto-repeat for state/action purposes.
            # If this key's original key-down was suppressed, continue
            # suppressing its repeated key-down events.
            if key in self.held_keys:
                return key in self.suppressed_keys

            self.held_keys.add(key)

            # Process the action first. This is important because a
            # combination becomes complete when the final key arrives.
            self._on_key_press(key)

            suppress = self._should_suppress_key(key)

            if suppress:
                self.suppressed_keys.add(key)

            return suppress

        # ----------------------------------------------------------
        # KEY UP
        # ----------------------------------------------------------

        if is_key_up:

            # IMPORTANT:
            # Only suppress a key-up if THAT SAME KEY'S key-down was
            # suppressed.
            #
            # Example Shift + A:
            #
            # Shift DOWN -> allowed
            # A DOWN     -> suppressed
            # A UP       -> suppressed
            # Shift UP   -> allowed
            #
            # This prevents Shift from becoming stuck.
            suppress = key in self.suppressed_keys

            self._on_key_release(key)

            self.held_keys.discard(key)
            self.suppressed_keys.discard(key)

            return suppress

        return False

    # ==============================================================
    # VK -> normalized key
    # ==============================================================

    @staticmethod
    def _vk_to_key(vk):

        # A-Z
        if 0x41 <= vk <= 0x5A:
            return chr(vk).lower()

        # 0-9
        if 0x30 <= vk <= 0x39:
            return chr(vk)

        # Numpad 0-9
        if 0x60 <= vk <= 0x69:
            return str(vk - 0x60)

        # F1-F12
        if 0x70 <= vk <= 0x7B:
            return f"f{vk - 0x6F}"

        return {
            # Modifiers
            0x10: "shift",
            0xA0: "shift",
            0xA1: "shift",

            0x11: "ctrl",
            0xA2: "ctrl",
            0xA3: "ctrl",

            0x12: "alt",
            0xA4: "alt",
            0xA5: "alt",

            0x5B: "win",
            0x5C: "win",

            # Basic keys
            0x08: "backspace",
            0x09: "tab",
            0x0D: "enter",
            0x1B: "esc",
            0x20: "space",

            # Navigation
            0x21: "pageup",
            0x22: "pagedown",
            0x23: "end",
            0x24: "home",
            0x25: "left",
            0x26: "up",
            0x27: "right",
            0x28: "down",
            0x2D: "insert",
            0x2E: "delete",

            # OEM punctuation
            0xBA: ";",
            0xBB: "=",
            0xBC: ",",
            0xBD: "-",
            0xBE: ".",
            0xBF: "/",
            0xC0: "`",
            0xDB: "[",
            0xDC: "\\",
            0xDD: "]",
            0xDE: "'",

            # Locks
            0x14: "capslock",
            0x90: "numlock",
            0x91: "scrolllock",

            # Misc
            0x2C: "printscreen",
            0x13: "pause",
        }.get(vk)

    # ==============================================================
    # Key press
    # ==============================================================

    def _on_key_press(self, key):

        mode1 = self._get_mode("Mode1")
        mode2 = self._get_mode("Mode2")

        # ----------------------------------------------------------
        # Mode 1 toggle
        # ----------------------------------------------------------

        combo = self._get_combo(
            "Mode1",
            "Toggle",
        )

        if self._combo_is_held(
            combo,
            self.held_keys,
        ):
            self._activate_once(
                combo,
                self._toggle_mode1,
            )

        # ----------------------------------------------------------
        # Mode 2 toggle
        # ----------------------------------------------------------

        combo = self._get_combo(
            "Mode2",
            "Toggle",
        )

        if self._combo_is_held(
            combo,
            self.held_keys,
        ):
            self._activate_once(
                combo,
                self._toggle_mode2,
            )

        # ----------------------------------------------------------
        # Mode 1 trigger
        # ----------------------------------------------------------

        if mode1.get("Enabled", True):

            combo = self._get_combo(
                "Mode1",
                "Trigger",
            )

            if self._combo_is_held(
                combo,
                self.held_keys,
            ):
                self._activate_mode1_trigger(combo)

        # ----------------------------------------------------------
        # Mode 2 mouse key
        # ----------------------------------------------------------

        if mode2.get("Enabled", False):

            combo = self._get_combo(
                "Mode2",
                "MouseKey",
            )

            if self._combo_is_held(
                combo,
                self.held_keys,
            ):
                self._mode2_mouse_pressed(combo)

        # ----------------------------------------------------------
        # Mode 2 back key
        # ----------------------------------------------------------

        if mode2.get("Enabled", False):

            combo = self._get_combo(
                "Mode2",
                "BackKey",
            )

            if self._combo_is_held(
                combo,
                self.held_keys,
            ):
                self._activate_once(
                    combo,
                    self._mode2_back_pressed,
                )

    # ==============================================================
    # Key release
    # ==============================================================

    def _on_key_release(self, key):

        mode1 = self._get_mode("Mode1")
        mode2 = self._get_mode("Mode2")

        # ----------------------------------------------------------
        # Mode 1
        # ----------------------------------------------------------

        trigger = self._get_combo(
            "Mode1",
            "Trigger",
        )

        remaining = self.held_keys - {key}

        if trigger and not self._combo_is_held(
            trigger,
            remaining,
        ):
            if self.mode1_rapid_active:
                self.macro.stop_rapid_click()
                self.mode1_rapid_active = False

        # ----------------------------------------------------------
        # Mode 2 mouse
        # ----------------------------------------------------------

        mouse_combo = self._get_combo(
            "Mode2",
            "MouseKey",
        )

        if mode2.get("Enabled", False):

            if mouse_combo and not self._combo_is_held(
                mouse_combo,
                remaining,
            ):
                self._mode2_mouse_released()

        # ----------------------------------------------------------
        # One-shot combinations
        # ----------------------------------------------------------

        for combo in list(self.active_combos):

            combo_set = set(combo)

            if not self._combo_is_held(
                combo_set,
                remaining,
            ):
                self.active_combos.discard(combo)

    # ==============================================================
    # Suppression
    # ==============================================================

    def _should_suppress_key(self, key):

        mode1 = self._get_mode("Mode1")
        mode2 = self._get_mode("Mode2")

        controls = []

        # Mode 1 toggle is always intercepted.
        controls.append(
            self._get_combo(
                "Mode1",
                "Toggle",
            )
        )

        # Mode 1 trigger only while enabled.
        if mode1.get("Enabled", True):
            controls.append(
                self._get_combo(
                    "Mode1",
                    "Trigger",
                )
            )

        # Mode 2 toggle is always intercepted.
        controls.append(
            self._get_combo(
                "Mode2",
                "Toggle",
            )
        )

        # Mode 2 controls only while enabled.
        if mode2.get("Enabled", False):

            controls.append(
                self._get_combo(
                    "Mode2",
                    "MouseKey",
                )
            )

            controls.append(
                self._get_combo(
                    "Mode2",
                    "BackKey",
                )
            )

        for combo in controls:

            if not combo:
                continue

            # Single-key mapping.
            if len(combo) == 1 and key in combo:
                return True

            # Combination mapping.
            #
            # Only the final key that completes the combination needs
            # to be suppressed on key-down. The modifier key-downs
            # remain normal Windows input.
            if len(combo) > 1:
                if self._combo_is_held(
                    combo,
                    self.held_keys,
                ):
                    return True

        return False

    # ==============================================================
    # One-shot
    # ==============================================================

    def _activate_once(self, combo, action):

        if not combo:
            return

        identifier = self._combo_key(combo)

        if identifier in self.active_combos:
            return

        self.active_combos.add(identifier)

        action()

    # ==============================================================
    # Mode 1
    # ==============================================================

    def _activate_mode1_trigger(self, combo):

        identifier = self._combo_key(combo)

        if identifier in self.active_combos:
            return

        self.active_combos.add(identifier)

        mode1 = self._get_mode("Mode1")

        behavior = str(
            mode1.get(
                "Behavior",
                "rapid",
            )
        ).lower()

        button = mode1.get(
            "MouseButton",
            "left",
        )

        # Single click mode.
        if behavior == "single":

            self.macro.click_once(button)

            return

        # Rapid click mode.
        interval = mode1.get(
            "Interval",
            30,
        )

        self.macro.start_rapid_click(
            button,
            interval,
        )

        self.mode1_rapid_active = True

    def _toggle_mode1(self):

        current = bool(
            self._get_mode("Mode1").get(
                "Enabled",
                True,
            )
        )

        enabled = not current

        self.settings.change_settings(
            "Mode1",
            "Enabled",
            newValue=enabled,
        )

        if not enabled:

            self.macro.stop_rapid_click()
            self.mode1_rapid_active = False

        self.main_app.reload_settings()

        self.main_app.set_status(
            "Mode 1 "
            + ("ON" if enabled else "OFF")
        )

    # ==============================================================
    # Mode 2
    # ==============================================================

    def _toggle_mode2(self):

        current = bool(
            self._get_mode("Mode2").get(
                "Enabled",
                False,
            )
        )

        enabled = not current

        self.settings.change_settings(
            "Mode2",
            "Enabled",
            newValue=enabled,
        )

        if not enabled:
            self._cancel_mode2_mouse()
            self.macro.stop_all()

        self.main_app.reload_settings()

        self.main_app.set_status(
            "Mode 2 "
            + ("ON" if enabled else "OFF")
        )

    def _mode2_mouse_pressed(self, combo):

        if self.mode2_mouse_active:
            return

        self.mode2_mouse_active = True
        self.mode2_mouse_hold = False

        if self.mode2_mouse_timer:
            self.mode2_mouse_timer.cancel()

        self.mode2_mouse_timer = threading.Timer(
            self.HOLD_THRESHOLD,
            self._start_mode2_hold,
        )

        self.mode2_mouse_timer.daemon = True
        self.mode2_mouse_timer.start()

    def _start_mode2_hold(self):

        with self._lock:

            if not self.mode2_mouse_active:
                return

            combo = self._get_combo(
                "Mode2",
                "MouseKey",
            )

            if not self._combo_is_held(
                combo,
                self.held_keys,
            ):
                return

            button = self._get_mode(
                "Mode2"
            ).get(
                "MouseButton",
                "left",
            )

            self.macro.mouse_down(button)

            self.mode2_mouse_hold = True

    def _mode2_mouse_released(self):

        if not self.mode2_mouse_active:
            return

        if self.mode2_mouse_timer:
            self.mode2_mouse_timer.cancel()
            self.mode2_mouse_timer = None

        button = self._get_mode(
            "Mode2"
        ).get(
            "MouseButton",
            "left",
        )

        if self.mode2_mouse_hold:

            self.macro.mouse_up(button)

        else:

            self.macro.click_once(button)

        self.mode2_mouse_active = False
        self.mode2_mouse_hold = False

    def _mode2_back_pressed(self):

        controller = keyboard.Controller()

        controller.press(keyboard.Key.esc)
        controller.release(keyboard.Key.esc)

    def _cancel_mode2_mouse(self):

        if self.mode2_mouse_timer:

            self.mode2_mouse_timer.cancel()
            self.mode2_mouse_timer = None

        if self.mode2_mouse_hold:

            button = self._get_mode(
                "Mode2"
            ).get(
                "MouseButton",
                "left",
            )

            self.macro.mouse_up(button)

        self.mode2_mouse_active = False
        self.mode2_mouse_hold = False

    # ==============================================================
    # Reload / shutdown
    # ==============================================================

    def reload_config(self):

        self.settings = self.main_app.settings

        if not self._get_mode(
            "Mode1"
        ).get(
            "Enabled",
            True,
        ):

            self.macro.stop_rapid_click()
            self.mode1_rapid_active = False

    def stop(self):

        self._cancel_mode2_mouse()

        self.macro.stop_all()

        if self.keyboard_hook:
            self.keyboard_hook.stop()

        self.held_keys.clear()
        self.suppressed_keys.clear()
        self.active_combos.clear()

    def unhook(self):
        self.stop()
